name: Module Lint

on:
  workflow_dispatch:

jobs:
  run-module-lint:
    name: Module Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - auto-changelog
          - create-release-branch
          - module-lint
          - utils
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run module-lint
        id: module-lint
        run: .github/scripts/run-module-lint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: ${{ matrix.project }}
    outputs:
      module-lint-outcome: ${{ steps.module-lint.outcome }}
  post-initial-message-to-slack:
    name: Post initial message to Slack
    needs: run-module-lint
    runs-on: ubuntu-latest
    steps:
      - name: Determine Slack payload
        id: slack-payload
        run: node .github/scripts/determine-initial-slack-payload.js
        env:
          MODULE_LINT_OUTCOME: ${{ needs.run-module-lint.outputs.module-lint-outcome }}
      - name: Post to Slack
        id: initial-slack-message
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          payload: ${{ steps.slack-payload.outputs.executable }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    outputs:
      slack-thread-ts: ${{ steps.initial-slack-message.outputs.ts }}
  post-threaded-message-to-slack:
    name: Post threaded message to Slack
    needs: post-initial-message-to-slack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - auto-changelog
          - create-release-branch
          - module-lint
          - utils
    steps:
      - name: Determine Slack payload
        id: slack-payload
        run: node .github/scripts/determine-slack-payload-for-package.js
        env:
          PACKAGE_NAME: ${{ matrix.project }}
          MODULE_LINT_OUTPUT_FILE: /tmp/module-lint/${{ matrix.project }}/output
          SLACK_CHANNEL_ID: C06S195ANA0 # Channel: #temp-test-module-lint
          SLACK_THREAD_TS: ${{ needs.post-initial-message-to-slack.outputs.slack-thread-ts }}
      - name: Post to Slack
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          payload: ${{ steps.slack-payload.outputs.executable }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
